# Generated by Django 3.1.5 on 2021-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='submission',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post_comment', to='post.PostComment'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='comments',
            field=models.ManyToManyField(related_name='_postcomment_comments_+', to='post.PostComment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
