# Generated by Django 3.1.5 on 2021-01-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddituser', '0002_auto_20210107_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='image',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images/'),
        ),
    ]
