# Generated by Django 3.1.5 on 2021-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddituser', '0003_reddituser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='image',
            field=models.ImageField(default='images-local/default_profile.jpg', upload_to='images/'),
        ),
    ]
