# Generated by Django 3.1.5 on 2021-01-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddituser', '0004_auto_20210118_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='image',
            field=models.ImageField(default='static/images-local/default_profile.jpg', upload_to='images/'),
        ),
    ]
