# Generated by Django 3.1.5 on 2021-01-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddituser', '0005_auto_20210118_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='image',
            field=models.ImageField(default='images/default_profile.png', upload_to='images/'),
        ),
    ]
