# Generated by Django 3.1.5 on 2021-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddituser', '0006_auto_20210118_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='image',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images/'),
        ),
    ]
