# Generated by Django 3.1.5 on 2021-01-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='about',
            field=models.CharField(max_length=100),
        ),
    ]
